export const REDIRECT_COMPLETE = 'REDIRECT_COMPLETE';

export const REQUEST_JOBS = 'REQUEST_JOBS';
export const RECEIVE_JOBS = 'RECEIVE_JOBS';
export const FILTER_JOBS = 'FILTER_JOBS';

export const CREATING_NEW_JOB = 'CREATING_NEW_JOB';
export const EDITING_JOB = 'EDITING_JOB';
export const REQUEST_JOB = 'REQUEST_JOB';
export const RECEIVE_JOB = 'RECEIVE_JOB';
export const UPDATED_JOB = 'UPDATED_JOB';
export const PREPARE_NEW_JOB = 'PREPARE_NEW_JOB';
export const RECEIVE_NEW_JOB = 'RECEIVE_NEW_JOB';
export const JOB_NOT_FOUND = 'JOB_NOT_FOUND';

export const SET_PREVIEW = 'SET_PREVIEW';
export const UNSET_PREVIEW = 'UNSET_PREVIEW';
